"""Shared dependency-free presentation and grid primitives for BitSquiggles."""

import math

STANDARD = "standard"
HIGH_CONTRAST = "high-contrast"
MONOCHROME = "monochrome"
BLACK_AND_WHITE = "black-and-white"
STYLES = (STANDARD, HIGH_CONTRAST, MONOCHROME, BLACK_AND_WHITE)

LEFT_RIGHT = "A|"
TOP_BOTTOM = "A-"
HALF_TURN = "A+"
DIAGONAL_SLASH = "A/"
MODES = (LEFT_RIGHT, TOP_BOTTOM, HALF_TURN, DIAGONAL_SLASH)

_DIMENSIONS32 = (7, 5, 58, 16, 22, 0xFFFFFFFF)
_DIMENSIONS40 = (7, 7, 84, 22, 22, 0xFFFFFFFFFF)

# BEGIN GENERATED PACKED TABLES
# Generated by generate_packed_tables.py; do not edit.
_MODE_TABLES32 = (
    (
        b"\x00\x06\x01\x08\x02\x04\x03\x07\x05\xff\x09\x0f\x0a\x11\x0b\x0d"
        b"\x0c\x10\x0e\xff\x12\x18\x13\x1a\x14\x16\x15\x19\x17\xff\x1b\x21"
        b"\x1c\x23\x1d\x1f\x1e\x22\x20\xff\x24\x2a\x25\x2c\x26\x28\x27\x2b"
        b"\x29\xff\x2d\x33\x2e\x35\x2f\x31\x30\x34\x32\xff\x36\x39\x37\x38"
    ),
    (
        b"\x00\x36\x01\x2e\x02\x37\x03\x30\x04\x38\x05\x32\x06\x39\x07\x34"
        b"\x08\x35\x09\x2d\x0a\x25\x0b\x2f\x0c\x27\x0d\x31\x0e\x29\x0f\x33"
        b"\x10\x2b\x11\x2c\x12\x24\x13\x1c\x14\x26\x15\x1e\x16\x28\x17\x20"
        b"\x18\x2a\x19\x22\x1a\x23\x1b\xff\x1d\xff\x1f\xff\x21\xff"
    ),
    (
        b"\x00\x39\x01\x35\x02\x38\x03\x34\x04\x37\x05\x32\x06\x36\x07\x30"
        b"\x08\x2e\x09\x33\x0a\x2c\x0b\x31\x0c\x2b\x0d\x2f\x0e\x29\x0f\x2d"
        b"\x10\x27\x11\x25\x12\x2a\x13\x23\x14\x28\x15\x22\x16\x26\x17\x20"
        b"\x18\x24\x19\x1e\x1a\x1c\x1b\x21\x1d\x1f"
    ),
    (
        b"\x00\x39\x01\x35\x02\x38\x03\xff\x34\xff\x04\x37\x05\xff\x32\xff"
        b"\x06\x36\x07\xff\x30\xff\x08\xff\x2e\xff\x09\x2c\x0a\x33\x0b\x23"
        b"\x0c\x2a\x0d\x1a\x0e\x21\x0f\x11\x10\x18\x12\x2b\x13\x31\x14\x22"
        b"\x15\x28\x16\x19\x17\x1f\x1b\x29\x1c\x2f\x1d\x20\x1e\x26\x24\x27"
        b"\x25\x2d"
    ),
)
_MODE_TABLES40 = (
    (
        b"\x00\x0a\x01\x0c\x02\x08\x03\x0b\x04\x06\x05\x09\x07\xff\x0d\x17"
        b"\x0e\x19\x0f\x15\x10\x18\x11\x13\x12\x16\x14\xff\x1a\x24\x1b\x26"
        b"\x1c\x22\x1d\x25\x1e\x20\x1f\x23\xa1\xff\x27\x31\x28\x33\x29\x2f"
        b"\x2a\x32\xab\x2d\x2c\x30\xae\xff\x34\x3e\x35\x40\x36\x3c\x37\x3f"
        b"\x38\x3a\x39\x3d\x3b\xff\x41\x4b\x42\x4d\x43\x49\x44\x4c\x45\x47"
        b"\x46\x4a\x48\xff\x4e\x53\x4f\x52\x50\x51"
    ),
    (
        b"\x00\x4e\x01\x42\x02\x4f\x03\x44\x04\x50\x05\x46\x06\x51\x07\x48"
        b"\x08\x52\x09\x4a\x0a\x53\x0b\x4c\x0c\x4d\x0d\x41\x0e\x35\x0f\x43"
        b"\x10\x37\x11\x45\x12\x39\x13\x47\x14\x3b\x15\x49\x16\x3d\x17\x4b"
        b"\x18\x3f\x19\x40\x1a\x34\x1b\x28\x1c\x36\x1d\x2a\x1e\x38\x1f\x2c"
        b"\x20\x3a\xa1\x2e\x22\x3c\x23\x30\x24\x3e\x25\x32\x26\x33\x27\xff"
        b"\x29\xff\xab\xff\xad\xff\x2f\xff\x31\xff"
    ),
    (
        b"\x00\x53\x01\x4d\x02\x52\x03\x4c\x04\x51\x05\x4a\x06\x50\x07\x48"
        b"\x08\x4f\x09\x46\x0a\x4e\x0b\x44\x0c\x42\x0d\x4b\x0e\x40\x0f\x49"
        b"\x10\x3f\x11\x47\x12\x3d\x13\x45\x14\x3b\x15\x43\x16\x39\x17\x41"
        b"\x18\x37\x19\x35\x1a\x3e\x1b\x33\x1c\x3c\x1d\x32\x1e\x3a\x1f\x30"
        b"\x20\x38\xa1\x2e\x22\x36\x23\x2c\x24\x34\x25\x2a\x26\x28\x27\x31"
        b"\x29\x2f\xab\x2d"
    ),
    (
        b"\x00\x4d\x01\x53\x02\x40\x03\x4b\x04\x33\x05\x3e\x06\x26\x07\x31"
        b"\x08\x19\x09\x24\x0a\x0c\x0b\x17\x0d\x4c\x0e\x52\x0f\x3f\x10\x49"
        b"\x11\x32\x12\x3c\x13\x25\x14\x2f\x15\x18\x16\x22\x1a\x4a\x1b\x51"
        b"\x1c\x3d\x1d\x47\x1e\x30\x1f\x3a\x20\x23\xa1\x2d\x27\x48\x28\x50"
        b"\x29\x3b\x2a\x45\xab\x2e\x2c\x38\x34\x46\x35\x4f\x36\x39\x37\x43"
        b"\x41\x44\x42\x4e"
    ),
)
_MARKER_INDICES40 = b"\x21\x2b\x2d\x2e"
# END GENERATED PACKED TABLES


def _dimensions(width):
    if width == 32:
        return _DIMENSIONS32
    if width == 40:
        return _DIMENSIONS40
    raise ValueError("width must be 32 or 40")


def _mode_tables(width):
    _dimensions(width)
    return _MODE_TABLES32 if width == 32 else _MODE_TABLES40


def _edge_at(rows, columns, index):
    row_span = 2 * columns - 1
    final_row_start = (rows - 1) * row_span
    if index >= final_row_start:
        column = index - final_row_start
        return rows - 1, column, rows - 1, column + 1
    row = index // row_span
    position = index % row_span
    if position == row_span - 1:
        return row, columns - 1, row + 1, columns - 1
    column = position // 2
    if position & 1:
        return row, column, row + 1, column
    return row, column, row, column + 1


def _edge_index(rows, columns, start_row, start_column, end_row, end_column):
    if (
        start_row == end_row
        and end_column == start_column + 1
        and 0 <= start_row < rows
        and 0 <= start_column < columns - 1
    ):
        if start_row == rows - 1:
            return (rows - 1) * (2 * columns - 1) + start_column
        return start_row * (2 * columns - 1) + 2 * start_column
    if (
        end_row == start_row + 1
        and start_column == end_column
        and 0 <= start_row < rows - 1
        and 0 <= start_column < columns
    ):
        position = (
            2 * start_column + 1 if start_column < columns - 1 else 2 * columns - 2
        )
        return start_row * (2 * columns - 1) + position
    raise ValueError("coordinates do not identify a canonical edge")


def _popcount(value):
    count = 0
    while value:
        value &= value - 1
        count += 1
    return count


def _active_cells(connections, rows, columns):
    cells = [[0 for _ in range(columns)] for _ in range(rows)]
    for index in range(len(connections)):
        if connections[index]:
            start_row, start_column, end_row, end_column = _edge_at(
                rows, columns, index
            )
            cells[start_row][start_column] = 1
            cells[end_row][end_column] = 1
    return cells


def _clamp01(value):
    return max(0.0, min(1.0, value))


def _srgb_encode(value):
    value = _clamp01(value)
    if value <= 0.0031308:
        return 12.92 * value
    return 1.055 * math.pow(value, 1.0 / 2.4) - 0.055


def _make_color(lightness, chroma, hue):
    radians = hue * math.pi / 180.0
    a = chroma * math.cos(radians)
    b = chroma * math.sin(radians)
    l_value = lightness + 0.3963377774 * a + 0.2158037573 * b
    m_value = lightness - 0.1055613458 * a - 0.0638541728 * b
    s_value = lightness - 0.0894841775 * a - 1.2914855480 * b
    l3, m3, s3 = l_value**3, m_value**3, s_value**3
    red = _srgb_encode(4.0767416621 * l3 - 3.3077115913 * m3 + 0.2309699292 * s3)
    green = _srgb_encode(-1.2684380046 * l3 + 2.6097574011 * m3 - 0.3413193965 * s3)
    blue = _srgb_encode(-0.0041960863 * l3 - 0.7034186147 * m3 + 1.7076147010 * s3)
    red = max(0, min(255, int(red * 255 + 0.5)))
    green = max(0, min(255, int(green * 255 + 0.5)))
    blue = max(0, min(255, int(blue * 255 + 0.5)))
    return {
        "L": lightness,
        "C": chroma,
        "h": hue,
        "hex": "#%02x%02x%02x" % (red, green, blue),
    }


def _derive_colors(mixed, input_value, style):
    if style not in STYLES:
        raise ValueError("unknown style: %s" % style)
    hue = ((mixed >> 12) & 0xF) * 22.5
    chroma = 0.05 + ((mixed >> 8) & 0xF) * (0.2 / 15.0)
    base_lightness = 0.5 + (mixed & 0x3) * (0.2 / 3.0)
    foreground_lightness = base_lightness
    background_lightness = foreground_lightness - 0.5
    foreground_chroma = chroma
    background_chroma = chroma
    if style != "standard":
        foreground_lightness = (
            1.0 if style == "black-and-white" else base_lightness + 0.3
        )
        background_lightness = (
            0.0 if style == "black-and-white" else foreground_lightness - 0.8
        )
        foreground_chroma = (
            0.0 if style in ("monochrome", "black-and-white") else chroma + 0.1
        )
        background_chroma = foreground_chroma
    foreground_lightness = _clamp01(foreground_lightness)
    background_lightness = _clamp01(background_lightness)
    if _popcount(input_value) & 1:
        foreground_lightness, background_lightness = (
            background_lightness,
            foreground_lightness,
        )
    return (
        _make_color(background_lightness, background_chroma, (hue + 180.0) % 360.0),
        _make_color(foreground_lightness, foreground_chroma, hue),
    )


def _generate_pixels(connections, rows, columns):
    width, height = 3 * columns + 1, 3 * rows + 1
    result = bytearray(width * height)
    cells = _active_cells(connections, rows, columns)
    for row in range(rows):
        for column in range(columns):
            if cells[row][column]:
                x, y = 1 + column * 3, 1 + row * 3
                result[y * width + x] = result[y * width + x + 1] = 1
                result[(y + 1) * width + x] = result[(y + 1) * width + x + 1] = 1
    for index in range(len(connections)):
        if connections[index]:
            start_row, start_column, end_row, _ = _edge_at(rows, columns, index)
            x, y = 1 + start_column * 3, 1 + start_row * 3
            if start_row == end_row:
                result[y * width + x + 2] = result[(y + 1) * width + x + 2] = 1
            else:
                result[(y + 2) * width + x] = result[(y + 2) * width + x + 1] = 1
    for row in range(rows - 1):
        for column in range(columns - 1):
            surrounding = (
                _edge_index(rows, columns, row, column, row, column + 1),
                _edge_index(rows, columns, row + 1, column, row + 1, column + 1),
                _edge_index(rows, columns, row, column, row + 1, column),
                _edge_index(rows, columns, row, column + 1, row + 1, column + 1),
            )
            if all(connections[index] for index in surrounding):
                result[(3 + row * 3) * width + 3 + column * 3] = 1
    return result


def _smooth_blobs(connections, rows, columns):
    edge_count = rows * (columns - 1) + (rows - 1) * columns
    if connections is None or len(connections) != edge_count:
        raise ValueError("connections must contain %d entries" % edge_count)
    required_edges = 0
    for index, value in enumerate(connections):
        if value not in (0, 1):
            raise ValueError("connections must contain only zeroes and ones")
        if value:
            required_edges |= 1 << index

    def rectangle_edges(top, left, bottom, right):
        mask = 0
        for row in range(top, bottom + 1):
            for column in range(left, right + 1):
                if column < right:
                    edge_index = _edge_index(
                        rows, columns, row, column, row, column + 1
                    )
                    bit = 1 << edge_index
                    if not required_edges & bit:
                        return 0
                    mask |= bit
                if row < bottom:
                    edge_index = _edge_index(
                        rows, columns, row, column, row + 1, column
                    )
                    bit = 1 << edge_index
                    if not required_edges & bit:
                        return 0
                    mask |= bit
        return mask

    required_junctions = 0
    for row in range(rows - 1):
        for column in range(columns - 1):
            if rectangle_edges(row, column, row + 1, column + 1):
                required_junctions |= 1 << (row * (columns - 1) + column)

    def rectangle_junctions(top, left, bottom, right):
        mask = 0
        for row in range(top, bottom):
            for column in range(left, right):
                bit = 1 << (row * (columns - 1) + column)
                if required_junctions & bit:
                    mask |= bit
        return mask

    covered_edges = covered_junctions = 0
    result = []
    while covered_edges != required_edges or covered_junctions != required_junctions:
        remaining = required_edges & ~covered_edges
        if remaining:
            anchor = (remaining & -remaining).bit_length() - 1
            anchor_top, anchor_left, anchor_bottom, anchor_right = _edge_at(
                rows, columns, anchor
            )
        else:
            remaining = required_junctions & ~covered_junctions
            anchor = (remaining & -remaining).bit_length() - 1
            anchor_top = anchor // (columns - 1)
            anchor_left = anchor % (columns - 1)
            anchor_bottom, anchor_right = anchor_top + 1, anchor_left + 1
        best = None
        for top in range(anchor_top, -1, -1):
            for left in range(anchor_left, -1, -1):
                for bottom in range(anchor_bottom, rows):
                    for right in range(anchor_right, columns):
                        candidate_edges = rectangle_edges(top, left, bottom, right)
                        if not candidate_edges:
                            continue
                        candidate_junctions = rectangle_junctions(
                            top, left, bottom, right
                        )
                        new_edges = candidate_edges & ~covered_edges
                        new_junctions = candidate_junctions & ~covered_junctions
                        candidate = (top, left, bottom, right)
                        score = (
                            _popcount(new_junctions),
                            _popcount(new_edges),
                            -(bottom - top + 1) * (right - left + 1),
                            -top,
                            -left,
                            -bottom,
                            -right,
                        )
                        if (new_edges or new_junctions) and (
                            best is None or score > best[0]
                        ):
                            best = (
                                score,
                                candidate,
                                candidate_edges,
                                candidate_junctions,
                            )
        if best is None:
            raise RuntimeError("uncoverable smooth feature")
        result.append(best[1])
        covered_edges |= best[2]
        covered_junctions |= best[3]
    return tuple(result)


# BitSquiggle32 encoding


def _mix32(value):
    value = (value + 0x9E3779B9) & 0xFFFFFFFF
    value ^= value >> 16
    value = (value * 0x85EBCA6B) & 0xFFFFFFFF
    value ^= value >> 13
    value = (value * 0xC2B2AE35) & 0xFFFFFFFF
    return (value ^ (value >> 16)) & 0xFFFFFFFF


def _encode(table, value, bit_width, edge_count):
    connections = bytearray(edge_count)
    usable_index = 0
    for index in range(0, len(table), 2):
        first = table[index]
        second = table[index + 1]
        excluded = first & 0x80
        selected = (
            0 if excluded else (value >> (bit_width - 1 - usable_index % bit_width)) & 1
        )
        connections[first & 0x7F] = selected
        if second != 0xFF:
            connections[second] = selected
        if not excluded:
            usable_index += 1
    return connections


def _encode32(mixed, mode_index):
    width = 32 if mode_index == 0 else 30
    value = mixed if mode_index == 0 else mixed & 0x3FFFFFFF
    return _encode(_MODE_TABLES32[mode_index], value, width, 58)


def _has_capacity32(mixed, mode_index):
    missing_bits = 30 - len(_MODE_TABLES32[mode_index]) // 2
    return missing_bits <= 0 or (mixed & ((1 << missing_bits) - 1)) == 0


# BitSquiggle40 encoding

_CHECKSUM_CHARSET = "qpzry9x8gf2tvdw0s3jn54khce6mua7l"


def _mix40(value):
    value = (value + 0xB97F4A7C15) & 0xFFFFFFFFFF
    value = ((value ^ (value >> 20)) * 0xD7ED558CCD) & 0xFFFFFFFFFF
    value = ((value ^ (value >> 15)) * 0xFE1A85EC53) & 0xFFFFFFFFFF
    return (value ^ (value >> 20)) & 0xFFFFFFFFFF


def _encode40(value, mode_index):
    width = 40 if mode_index == 0 else 38
    return _encode(_MODE_TABLES40[mode_index], value, width, 84)


def _apply_marker40(connections):
    for edge_index in _MARKER_INDICES40:
        connections[edge_index] = 0
    connections[_MARKER_INDICES40[0]] = 1


def bip380_checksum_input(checksum):
    if not isinstance(checksum, str) or len(checksum) != 8:
        raise ValueError("checksum must contain exactly eight characters")
    value = 0
    for character in checksum:
        symbol = _CHECKSUM_CHARSET.find(character)
        if symbol < 0:
            raise ValueError("invalid BIP380 checksum character")
        value = (value << 5) | symbol
    return value


# Common variant dispatch and presentation


def _definition(table, has_exclusions):
    classes = []
    excluded = []
    for index in range(0, len(table), 2):
        first = table[index]
        second = table[index + 1]
        classes.append((first & 0x7F,) if second == 0xFF else (first & 0x7F, second))
        excluded.append(bool(first & 0x80))
    classes = tuple(classes)
    excluded = tuple(excluded) if has_exclusions else ()
    usable = (
        tuple(
            occurrences
            for index, occurrences in enumerate(classes)
            if not excluded[index]
        )
        if excluded
        else classes
    )
    return {"classes": classes, "usable": usable, "excluded": excluded}


def variant(width):
    rows, columns, edge_count, pixel_width, pixel_height, mask = _dimensions(width)
    selected = {
        "width": width,
        "rows": rows,
        "columns": columns,
        "edge_count": edge_count,
        "pixel_width": pixel_width,
        "pixel_height": pixel_height,
        "mask": mask,
        "edges": edges(width),
        "definitions": tuple(
            _definition(table, width == 40) for table in _mode_tables(width)
        ),
    }
    if width == 40:
        selected["marker_indices"] = tuple(_MARKER_INDICES40)
    return selected


def _validate_input(width, mask, value):
    if not isinstance(value, int) or value < 0 or value > mask:
        raise ValueError("bits must be an unsigned %d-bit integer" % width)


def mix(width, value):
    mask = _dimensions(width)[5]
    _validate_input(width, mask, value)
    return _mix32(value) if width == 32 else _mix40(value)


def edges(width):
    rows, columns, edge_count, _, _, _ = _dimensions(width)
    return tuple(_edge_at(rows, columns, index) for index in range(edge_count))


def free_connection_count(width, mode):
    return len(_mode_tables(width)[MODES.index(mode)]) // 2


def usable_connection_count(width, mode):
    table = _mode_tables(width)[MODES.index(mode)]
    return sum(not table[index] & 0x80 for index in range(0, len(table), 2))


def matches_mode(width, connections, mode):
    edge_count = _dimensions(width)[2]
    if connections is None or len(connections) != edge_count:
        return False
    table = _mode_tables(width)[MODES.index(mode)]
    for index in range(0, len(table), 2):
        first = table[index]
        second = table[index + 1]
        expected = connections[first & 0x7F]
        if first & 0x80 and expected:
            return False
        if second != 0xFF and connections[second] != expected:
            return False
    return True


def _conflicts_with_earlier_mode(width, connections, mode_index):
    return any(
        matches_mode(width, connections, MODES[earlier])
        for earlier in range(mode_index)
    )


def _connections32(mixed):
    mode_index = mixed >> 30
    candidate = _encode32(mixed, mode_index)
    fallback = mode_index != 0 and (
        not _has_capacity32(mixed, mode_index)
        or _conflicts_with_earlier_mode(32, candidate, mode_index)
    )
    return (
        _encode32(mixed, 0) if fallback else candidate,
        mode_index,
        0 if fallback else mode_index,
        fallback,
    )


def _connections40(mixed):
    mode_index = mixed >> 38
    payload = mixed & 0x3FFFFFFFFF
    candidate = _encode40(mixed if mode_index == 0 else payload, mode_index)
    fallback = mode_index != 0 and _conflicts_with_earlier_mode(
        40, candidate, mode_index
    )
    connections = _encode40(mixed, 0) if fallback else candidate
    _apply_marker40(connections)
    return connections, mode_index, 0 if fallback else mode_index, fallback


def spec(width, bits, style=STANDARD):
    rows, columns, _, _, _, mask = _dimensions(width)
    _validate_input(width, mask, bits)
    if style not in STYLES:
        raise ValueError("unknown style: %s" % style)
    mixed = mix(width, bits)
    if width == 32:
        connections, preferred, actual, fallback = _connections32(mixed)
    else:
        connections, preferred, actual, fallback = _connections40(mixed)
    background, foreground = _derive_colors(mixed, bits, style)
    return {
        "input": bits,
        "mixed": mixed,
        "connections": connections,
        "cells": _active_cells(connections, rows, columns),
        "background": background,
        "foreground": foreground,
        "style": style,
        "preferred_mode": MODES[preferred],
        "actual_mode": MODES[actual],
        "fallback": fallback,
        "luminance_index": mixed & 0x3,
        "swapped": (_popcount(bits) & 1) == 1,
    }


def pixels(width, bits, style=STANDARD):
    rows, columns, _, pixel_width, pixel_height, _ = _dimensions(width)
    visual = spec(width, bits, style)
    return {
        "width": pixel_width,
        "height": pixel_height,
        "pixels": _generate_pixels(
            visual["connections"],
            rows,
            columns,
        ),
        "background": visual["background"],
        "foreground": visual["foreground"],
        "style": style,
    }


def smooth_blobs(width, connections):
    rows, columns, _, _, _, _ = _dimensions(width)
    return _smooth_blobs(connections, rows, columns)


def connection(width, connections, start_row, start_column, end_row, end_column):
    rows, columns, _, _, _, _ = _dimensions(width)
    index = _edge_index(rows, columns, start_row, start_column, end_row, end_column)
    return connections[index]


def active_cells(width, connections):
    rows, columns, _, _, _, _ = _dimensions(width)
    return _active_cells(connections, rows, columns)


def validate_grid(width, grid):
    _, _, _, pixel_width, pixel_height, _ = _dimensions(width)
    try:
        grid_width = grid["width"]
        grid_height = grid["height"]
        pixel_data = grid["pixels"]
        background = grid["background"]["hex"]
        foreground = grid["foreground"]["hex"]
    except (KeyError, TypeError):
        raise ValueError("grid must be a BitSquiggles pixel grid")
    if (grid_width, grid_height) != (pixel_width, pixel_height):
        raise ValueError("grid does not match the selected BitSquiggles width")
    if len(pixel_data) != grid_width * grid_height:
        raise ValueError("grid has an invalid pixel buffer")
    for pixel in pixel_data:
        if pixel not in (0, 1):
            raise ValueError("grid pixels must contain only zeroes and ones")
    return grid_width, grid_height, pixel_data, background, foreground


def validate_visual(width, visual):
    edge_count = _dimensions(width)[2]
    try:
        connections = visual["connections"]
    except (KeyError, TypeError):
        raise ValueError("visual must be a BitSquiggles specification")
    if len(connections) != edge_count:
        raise ValueError("visual does not match the selected BitSquiggles width")
    return connections


def warn_deprecated(old_name, replacement):
    try:
        import warnings
    except ImportError:
        return
    warnings.warn(
        "%s() is deprecated; use %s()" % (old_name, replacement),
        DeprecationWarning,
        stacklevel=3,
    )
