#include "bitsquiggles_core.h"

#include <math.h>
#include <stdio.h>
#include <string.h>

/* BEGIN GENERATED MODE TABLES */
/* Generated by generate_packed_tables.py; do not edit. */
static const uint8_t MODE_TABLES32[] = {
    0x00u, 0x06u, 0x01u, 0x08u, 0x02u, 0x04u, 0x03u, 0x07u,
    0x05u, 0xffu, 0x09u, 0x0fu, 0x0au, 0x11u, 0x0bu, 0x0du,
    0x0cu, 0x10u, 0x0eu, 0xffu, 0x12u, 0x18u, 0x13u, 0x1au,
    0x14u, 0x16u, 0x15u, 0x19u, 0x17u, 0xffu, 0x1bu, 0x21u,
    0x1cu, 0x23u, 0x1du, 0x1fu, 0x1eu, 0x22u, 0x20u, 0xffu,
    0x24u, 0x2au, 0x25u, 0x2cu, 0x26u, 0x28u, 0x27u, 0x2bu,
    0x29u, 0xffu, 0x2du, 0x33u, 0x2eu, 0x35u, 0x2fu, 0x31u,
    0x30u, 0x34u, 0x32u, 0xffu, 0x36u, 0x39u, 0x37u, 0x38u,
    0x00u, 0x36u, 0x01u, 0x2eu, 0x02u, 0x37u, 0x03u, 0x30u,
    0x04u, 0x38u, 0x05u, 0x32u, 0x06u, 0x39u, 0x07u, 0x34u,
    0x08u, 0x35u, 0x09u, 0x2du, 0x0au, 0x25u, 0x0bu, 0x2fu,
    0x0cu, 0x27u, 0x0du, 0x31u, 0x0eu, 0x29u, 0x0fu, 0x33u,
    0x10u, 0x2bu, 0x11u, 0x2cu, 0x12u, 0x24u, 0x13u, 0x1cu,
    0x14u, 0x26u, 0x15u, 0x1eu, 0x16u, 0x28u, 0x17u, 0x20u,
    0x18u, 0x2au, 0x19u, 0x22u, 0x1au, 0x23u, 0x1bu, 0xffu,
    0x1du, 0xffu, 0x1fu, 0xffu, 0x21u, 0xffu, 0x00u, 0x39u,
    0x01u, 0x35u, 0x02u, 0x38u, 0x03u, 0x34u, 0x04u, 0x37u,
    0x05u, 0x32u, 0x06u, 0x36u, 0x07u, 0x30u, 0x08u, 0x2eu,
    0x09u, 0x33u, 0x0au, 0x2cu, 0x0bu, 0x31u, 0x0cu, 0x2bu,
    0x0du, 0x2fu, 0x0eu, 0x29u, 0x0fu, 0x2du, 0x10u, 0x27u,
    0x11u, 0x25u, 0x12u, 0x2au, 0x13u, 0x23u, 0x14u, 0x28u,
    0x15u, 0x22u, 0x16u, 0x26u, 0x17u, 0x20u, 0x18u, 0x24u,
    0x19u, 0x1eu, 0x1au, 0x1cu, 0x1bu, 0x21u, 0x1du, 0x1fu,
    0x00u, 0x39u, 0x01u, 0x35u, 0x02u, 0x38u, 0x03u, 0xffu,
    0x34u, 0xffu, 0x04u, 0x37u, 0x05u, 0xffu, 0x32u, 0xffu,
    0x06u, 0x36u, 0x07u, 0xffu, 0x30u, 0xffu, 0x08u, 0xffu,
    0x2eu, 0xffu, 0x09u, 0x2cu, 0x0au, 0x33u, 0x0bu, 0x23u,
    0x0cu, 0x2au, 0x0du, 0x1au, 0x0eu, 0x21u, 0x0fu, 0x11u,
    0x10u, 0x18u, 0x12u, 0x2bu, 0x13u, 0x31u, 0x14u, 0x22u,
    0x15u, 0x28u, 0x16u, 0x19u, 0x17u, 0x1fu, 0x1bu, 0x29u,
    0x1cu, 0x2fu, 0x1du, 0x20u, 0x1eu, 0x26u, 0x24u, 0x27u,
    0x25u, 0x2du,
};
static const uint16_t MODE_OFFSETS32[] = {
    0x00u, 0x40u, 0x7eu, 0xb8u,
};
static const uint8_t MODE_COUNTS32[] = {
    0x20u, 0x1fu, 0x1du, 0x21u,
};
static const uint8_t MODE_TABLES40[] = {
    0x00u, 0x0au, 0x01u, 0x0cu, 0x02u, 0x08u, 0x03u, 0x0bu,
    0x04u, 0x06u, 0x05u, 0x09u, 0x07u, 0xffu, 0x0du, 0x17u,
    0x0eu, 0x19u, 0x0fu, 0x15u, 0x10u, 0x18u, 0x11u, 0x13u,
    0x12u, 0x16u, 0x14u, 0xffu, 0x1au, 0x24u, 0x1bu, 0x26u,
    0x1cu, 0x22u, 0x1du, 0x25u, 0x1eu, 0x20u, 0x1fu, 0x23u,
    0xa1u, 0xffu, 0x27u, 0x31u, 0x28u, 0x33u, 0x29u, 0x2fu,
    0x2au, 0x32u, 0xabu, 0x2du, 0x2cu, 0x30u, 0xaeu, 0xffu,
    0x34u, 0x3eu, 0x35u, 0x40u, 0x36u, 0x3cu, 0x37u, 0x3fu,
    0x38u, 0x3au, 0x39u, 0x3du, 0x3bu, 0xffu, 0x41u, 0x4bu,
    0x42u, 0x4du, 0x43u, 0x49u, 0x44u, 0x4cu, 0x45u, 0x47u,
    0x46u, 0x4au, 0x48u, 0xffu, 0x4eu, 0x53u, 0x4fu, 0x52u,
    0x50u, 0x51u, 0x00u, 0x4eu, 0x01u, 0x42u, 0x02u, 0x4fu,
    0x03u, 0x44u, 0x04u, 0x50u, 0x05u, 0x46u, 0x06u, 0x51u,
    0x07u, 0x48u, 0x08u, 0x52u, 0x09u, 0x4au, 0x0au, 0x53u,
    0x0bu, 0x4cu, 0x0cu, 0x4du, 0x0du, 0x41u, 0x0eu, 0x35u,
    0x0fu, 0x43u, 0x10u, 0x37u, 0x11u, 0x45u, 0x12u, 0x39u,
    0x13u, 0x47u, 0x14u, 0x3bu, 0x15u, 0x49u, 0x16u, 0x3du,
    0x17u, 0x4bu, 0x18u, 0x3fu, 0x19u, 0x40u, 0x1au, 0x34u,
    0x1bu, 0x28u, 0x1cu, 0x36u, 0x1du, 0x2au, 0x1eu, 0x38u,
    0x1fu, 0x2cu, 0x20u, 0x3au, 0xa1u, 0x2eu, 0x22u, 0x3cu,
    0x23u, 0x30u, 0x24u, 0x3eu, 0x25u, 0x32u, 0x26u, 0x33u,
    0x27u, 0xffu, 0x29u, 0xffu, 0xabu, 0xffu, 0xadu, 0xffu,
    0x2fu, 0xffu, 0x31u, 0xffu, 0x00u, 0x53u, 0x01u, 0x4du,
    0x02u, 0x52u, 0x03u, 0x4cu, 0x04u, 0x51u, 0x05u, 0x4au,
    0x06u, 0x50u, 0x07u, 0x48u, 0x08u, 0x4fu, 0x09u, 0x46u,
    0x0au, 0x4eu, 0x0bu, 0x44u, 0x0cu, 0x42u, 0x0du, 0x4bu,
    0x0eu, 0x40u, 0x0fu, 0x49u, 0x10u, 0x3fu, 0x11u, 0x47u,
    0x12u, 0x3du, 0x13u, 0x45u, 0x14u, 0x3bu, 0x15u, 0x43u,
    0x16u, 0x39u, 0x17u, 0x41u, 0x18u, 0x37u, 0x19u, 0x35u,
    0x1au, 0x3eu, 0x1bu, 0x33u, 0x1cu, 0x3cu, 0x1du, 0x32u,
    0x1eu, 0x3au, 0x1fu, 0x30u, 0x20u, 0x38u, 0xa1u, 0x2eu,
    0x22u, 0x36u, 0x23u, 0x2cu, 0x24u, 0x34u, 0x25u, 0x2au,
    0x26u, 0x28u, 0x27u, 0x31u, 0x29u, 0x2fu, 0xabu, 0x2du,
    0x00u, 0x4du, 0x01u, 0x53u, 0x02u, 0x40u, 0x03u, 0x4bu,
    0x04u, 0x33u, 0x05u, 0x3eu, 0x06u, 0x26u, 0x07u, 0x31u,
    0x08u, 0x19u, 0x09u, 0x24u, 0x0au, 0x0cu, 0x0bu, 0x17u,
    0x0du, 0x4cu, 0x0eu, 0x52u, 0x0fu, 0x3fu, 0x10u, 0x49u,
    0x11u, 0x32u, 0x12u, 0x3cu, 0x13u, 0x25u, 0x14u, 0x2fu,
    0x15u, 0x18u, 0x16u, 0x22u, 0x1au, 0x4au, 0x1bu, 0x51u,
    0x1cu, 0x3du, 0x1du, 0x47u, 0x1eu, 0x30u, 0x1fu, 0x3au,
    0x20u, 0x23u, 0xa1u, 0x2du, 0x27u, 0x48u, 0x28u, 0x50u,
    0x29u, 0x3bu, 0x2au, 0x45u, 0xabu, 0x2eu, 0x2cu, 0x38u,
    0x34u, 0x46u, 0x35u, 0x4fu, 0x36u, 0x39u, 0x37u, 0x43u,
    0x41u, 0x44u, 0x42u, 0x4eu,
};
static const uint16_t MODE_OFFSETS40[] = {
    0x00u, 0x5au, 0xb4u, 0x108u,
};
static const uint8_t MODE_COUNTS40[] = {
    0x2du, 0x2du, 0x2au, 0x2au,
};
static const uint8_t MARKER_INDICES[] = {
    0x21u, 0x2bu, 0x2du, 0x2eu,
};
/* END GENERATED MODE TABLES */

typedef struct {
  unsigned int rows;
  unsigned int columns;
  unsigned int edge_count;
  unsigned int pixel_width;
  unsigned int pixel_height;
  unsigned int max_smooth_blobs;
  unsigned int input_width;
  unsigned int payload_width;
  uint64_t input_mask;
  const uint8_t *mode_tables;
  const uint16_t *mode_offsets;
  const uint8_t *mode_counts;
  const uint8_t *marker_indices;
  unsigned int marker_count;
} BitsquigglesVariant;

static const BitsquigglesVariant VARIANT32 = {
  BITSQUIGGLES_ROWS,
  BITSQUIGGLES_32_COLUMNS,
  BITSQUIGGLES_32_EDGE_COUNT,
  BITSQUIGGLES_32_PIXEL_WIDTH,
  BITSQUIGGLES_PIXEL_HEIGHT,
  BITSQUIGGLES_32_MAX_SMOOTH_BLOBS,
  32u,
  30u,
  UINT32_MAX,
  MODE_TABLES32,
  MODE_OFFSETS32,
  MODE_COUNTS32,
  NULL,
  0u};

static const BitsquigglesVariant VARIANT40 = {
  BITSQUIGGLES_ROWS,
  BITSQUIGGLES_40_COLUMNS,
  BITSQUIGGLES_40_EDGE_COUNT,
  BITSQUIGGLES_40_PIXEL_WIDTH,
  BITSQUIGGLES_PIXEL_HEIGHT,
  BITSQUIGGLES_40_MAX_SMOOTH_BLOBS,
  40u,
  38u,
  BITSQUIGGLES_40_MASK,
  MODE_TABLES40,
  MODE_OFFSETS40,
  MODE_COUNTS40,
  MARKER_INDICES,
  4u};

static const BitsquigglesVariant *variant_for_width(BitsquigglesWidth width) {
  if (width == BITSQUIGGLES_32)
    return &VARIANT32;
  if (width == BITSQUIGGLES_40)
    return &VARIANT40;
  return NULL;
}

static bool valid_mode(unsigned int mode) { return mode < 4u; }

static const uint8_t *mode_table(const BitsquigglesVariant *variant,
                                 unsigned int mode) {
  return variant->mode_tables + variant->mode_offsets[mode];
}

static BitsquigglesEdge edge_at(const BitsquigglesVariant *variant,
                                unsigned int index) {
  BitsquigglesEdge edge;
  unsigned int row_span = 2u * variant->columns - 1u;
  unsigned int final_row_start = (variant->rows - 1u) * row_span;

  if (index >= final_row_start) {
    unsigned int column = index - final_row_start;
    edge.start_row = (uint8_t)(variant->rows - 1u);
    edge.start_column = (uint8_t)column;
    edge.end_row = edge.start_row;
    edge.end_column = (uint8_t)(column + 1u);
    return edge;
  }

  edge.start_row = (uint8_t)(index / row_span);
  index %= row_span;
  if (index == row_span - 1u) {
    edge.start_column = (uint8_t)(variant->columns - 1u);
    edge.end_row = (uint8_t)(edge.start_row + 1u);
    edge.end_column = edge.start_column;
  } else {
    edge.start_column = (uint8_t)(index / 2u);
    if ((index & 1u) != 0) {
      edge.end_row = (uint8_t)(edge.start_row + 1u);
      edge.end_column = edge.start_column;
    } else {
      edge.end_row = edge.start_row;
      edge.end_column = (uint8_t)(edge.start_column + 1u);
    }
  }
  return edge;
}

static unsigned int edge_index(const BitsquigglesVariant *variant,
                               unsigned int start_row,
                               unsigned int start_column,
                               unsigned int end_row) {
  unsigned int row_span = 2u * variant->columns - 1u;
  if (start_row == end_row) {
    if (start_row == variant->rows - 1u)
      return start_row * row_span + start_column;
    return start_row * row_span + 2u * start_column;
  }
  return start_row * row_span +
         (start_column == variant->columns - 1u ? row_span - 1u
                                                : 2u * start_column + 1u);
}

static void generate_edges(const BitsquigglesVariant *variant,
                           BitsquigglesEdge *output) {
  unsigned int row;
  unsigned int column;
  unsigned int index = 0;

  for (row = 0; row < variant->rows; ++row) {
    for (column = 0; column < variant->columns; ++column) {
      if (column + 1u < variant->columns) {
        output[index].start_row = (uint8_t)row;
        output[index].start_column = (uint8_t)column;
        output[index].end_row = (uint8_t)row;
        output[index].end_column = (uint8_t)(column + 1u);
        ++index;
      }
      if (row + 1u < variant->rows) {
        output[index].start_row = (uint8_t)row;
        output[index].start_column = (uint8_t)column;
        output[index].end_row = (uint8_t)(row + 1u);
        output[index].end_column = (uint8_t)column;
        ++index;
      }
    }
  }
}

static unsigned int
free_connection_count(const BitsquigglesVariant *variant, unsigned int mode) {
  if (variant == NULL || !valid_mode(mode))
    return 0;
  return variant->mode_counts[mode];
}

static unsigned int
usable_connection_count(const BitsquigglesVariant *variant,
                        unsigned int mode) {
  const uint8_t *table;
  unsigned int index;
  unsigned int count = 0;

  if (variant == NULL || !valid_mode(mode))
    return 0;
  table = mode_table(variant, mode);
  for (index = 0; index < variant->mode_counts[mode]; ++index) {
    if ((table[2u * index] & 0x80u) == 0)
      ++count;
  }
  return count;
}

static bool matches_mode(const BitsquigglesVariant *variant,
                         const uint8_t *connections, unsigned int mode) {
  const uint8_t *table;
  unsigned int index;

  if (variant == NULL || connections == NULL || !valid_mode(mode))
    return false;
  table = mode_table(variant, mode);
  for (index = 0; index < variant->mode_counts[mode]; ++index) {
    uint8_t first = table[2u * index];
    uint8_t second = table[2u * index + 1u];
    uint8_t expected = connections[first & 0x7fu];
    if ((first & 0x80u) != 0 && expected != 0)
      return false;
    if (second != 0xffu && connections[second] != expected)
      return false;
  }
  return true;
}

static void encode(const BitsquigglesVariant *variant, uint64_t mixed,
                   unsigned int mode, uint8_t *connections) {
  const uint8_t *table = mode_table(variant, mode);
  unsigned int bit_width = mode == 0 ? variant->input_width
                                     : variant->payload_width;
  unsigned int usable_index = 0;
  unsigned int index;
  uint64_t value = mode == 0
                       ? mixed
                       : mixed & ((UINT64_C(1) << variant->payload_width) - 1u);

  memset(connections, 0, variant->edge_count);
  for (index = 0; index < variant->mode_counts[mode]; ++index) {
    uint8_t first = table[2u * index];
    uint8_t second = table[2u * index + 1u];
    uint8_t bit;
    if ((first & 0x80u) != 0)
      continue;
    bit = (uint8_t)((value >>
                     (bit_width - 1u - usable_index++ % bit_width)) &
                    1u);
    connections[first] = bit;
    if (second != 0xffu)
      connections[second] = bit;
  }
}

static bool preferred_mode_has_capacity(const BitsquigglesVariant *variant,
                                        uint64_t mixed, unsigned int mode) {
  unsigned int count =
      usable_connection_count(variant, mode);
  unsigned int missing_bits;

  if (count >= variant->payload_width)
    return true;
  missing_bits = variant->payload_width - count;
  return (mixed & ((UINT64_C(1) << missing_bits) - 1u)) == 0;
}

static bool conflicts_with_earlier_mode(const BitsquigglesVariant *variant,
                                        const uint8_t *connections,
                                        unsigned int mode) {
  unsigned int earlier;
  for (earlier = 0; earlier < mode; ++earlier) {
    if (matches_mode(variant, connections, earlier))
      return true;
  }
  return false;
}

static void active_cells(const BitsquigglesVariant *variant,
                         const uint8_t *connections,
                         uint8_t cells[BITSQUIGGLES_ROWS]
                                      [BITSQUIGGLES_MAX_COLUMNS]) {
  unsigned int index;
  memset(cells, 0,
         BITSQUIGGLES_ROWS * BITSQUIGGLES_MAX_COLUMNS * sizeof(cells[0][0]));
  for (index = 0; index < variant->edge_count; ++index) {
    BitsquigglesEdge edge;
    if (connections[index] == 0)
      continue;
    edge = edge_at(variant, index);
    cells[edge.start_row][edge.start_column] = 1;
    cells[edge.end_row][edge.end_column] = 1;
  }
}

static unsigned int popcount64(uint64_t value) {
  unsigned int count = 0;
  while (value != 0) {
    value &= value - 1u;
    ++count;
  }
  return count;
}

static double clamp01(double value) {
  return value < 0 ? 0 : value > 1 ? 1 : value;
}

static double srgb(double value) {
  value = clamp01(value);
  return value <= .0031308 ? 12.92 * value : 1.055 * pow(value, 1 / 2.4) - .055;
}

static void make_color(double lightness, double chroma, double hue,
                       BitsquigglesColor *out) {
  double radians = hue * acos(-1) / 180, a = chroma * cos(radians),
         b = chroma * sin(radians),
         l = lightness + .3963377774 * a + .2158037573 * b,
         m = lightness - .1055613458 * a - .0638541728 * b,
         s = lightness - .0894841775 * a - 1.291485548 * b;
  int red = (int)(srgb(4.0767416621 * l * l * l - 3.3077115913 * m * m * m +
                       .2309699292 * s * s * s) *
                      255 +
                  .5),
      green = (int)(srgb(-1.2684380046 * l * l * l + 2.6097574011 * m * m * m -
                         .3413193965 * s * s * s) *
                        255 +
                    .5),
      blue = (int)(srgb(-.0041960863 * l * l * l - .7034186147 * m * m * m +
                        1.707614701 * s * s * s) *
                       255 +
                   .5);
  out->lightness = lightness;
  out->chroma = chroma;
  out->hue = hue;
  (void)snprintf(out->hex, sizeof out->hex, "#%02x%02x%02x", red, green, blue);
}

static void derive_colors(uint64_t mixed, uint64_t input, unsigned int style,
                          BitsquigglesColor *background,
                          BitsquigglesColor *foreground) {
  double hue = ((mixed >> 12) & 15) * 22.5,
         chroma = .05 + ((mixed >> 8) & 15) * (.2 / 15),
         base = .5 + (mixed & 3) * (.2 / 3), foreground_l = base,
         background_l = foreground_l - .5, foreground_c = chroma,
         background_c = chroma, temporary;
  if (style) {
    foreground_l = style == 3 ? 1 : base + .3;
    background_l = style == 3 ? 0 : foreground_l - .8;
    foreground_c = (style == 2 || style == 3) ? 0 : chroma + .1;
    background_c = foreground_c;
  }
  foreground_l = clamp01(foreground_l);
  background_l = clamp01(background_l);
  if (popcount64(input) & 1) {
    temporary = foreground_l;
    foreground_l = background_l;
    background_l = temporary;
  }
  make_color(background_l, background_c, fmod(hue + 180, 360), background);
  make_color(foreground_l, foreground_c, hue, foreground);
}

static uint64_t mix_value(const BitsquigglesVariant *variant, uint64_t value) {
  if (variant->input_width == 32u) {
    uint32_t narrowed = (uint32_t)value;
    narrowed += UINT32_C(0x9e3779b9);
    narrowed = (narrowed ^ (narrowed >> 16)) * UINT32_C(0x85ebca6b);
    narrowed = (narrowed ^ (narrowed >> 13)) * UINT32_C(0xc2b2ae35);
    return narrowed ^ (narrowed >> 16);
  }
  value = (value + UINT64_C(0xb97f4a7c15)) & BITSQUIGGLES_40_MASK;
  value = ((value ^ (value >> 20)) * UINT64_C(0xd7ed558ccd)) &
          BITSQUIGGLES_40_MASK;
  value = ((value ^ (value >> 15)) * UINT64_C(0xfe1a85ec53)) &
          BITSQUIGGLES_40_MASK;
  return (value ^ (value >> 20)) & BITSQUIGGLES_40_MASK;
}

static int generate_spec(const BitsquigglesVariant *variant, uint64_t input,
                         unsigned int style, BitsquigglesSpec *output) {
  uint8_t candidate[BITSQUIGGLES_MAX_EDGE_COUNT];
  uint64_t mixed;
  unsigned int mode;
  unsigned int index;
  bool fallback;

  if (variant == NULL || input > variant->input_mask || style > 3u ||
      output == NULL) {
    return -1;
  }

  memset(output, 0, sizeof(*output));
  mixed = mix_value(variant, input);
  mode = (unsigned int)(mixed >> variant->payload_width);
  encode(variant, mixed, mode, candidate);
  fallback = mode != 0 &&
             (!preferred_mode_has_capacity(variant, mixed, mode) ||
              conflicts_with_earlier_mode(variant, candidate, mode));
  if (fallback)
    encode(variant, mixed, 0, output->connections);
  else
    memcpy(output->connections, candidate, variant->edge_count);
  for (index = 0; index < variant->marker_count; ++index)
    output->connections[variant->marker_indices[index]] =
        (uint8_t)(index == 0);

  active_cells(variant, output->connections, output->cells);
  derive_colors(mixed, input, style, &output->background,
                &output->foreground);
  output->input = input;
  output->mixed = mixed;
  output->style = (BitsquigglesStyle)style;
  output->preferred_mode = (BitsquigglesMode)mode;
  output->actual_mode = (BitsquigglesMode)(fallback ? 0 : mode);
  output->fallback = fallback;
  output->luminance_index = (uint8_t)(mixed & 0x3u);
  output->swapped = (popcount64(input) & 1u) != 0;
  return 0;
}

static int generate_pixels(const BitsquigglesVariant *variant, uint64_t input,
                           unsigned int style,
                           BitsquigglesPixelGrid *output) {
  BitsquigglesSpec spec;
  unsigned int index;
  unsigned int row;
  unsigned int column;

  if (output == NULL || generate_spec(variant, input, style, &spec) != 0) {
    return -1;
  }

  memset(output, 0, sizeof(*output));
  for (row = 0; row < variant->rows; ++row) {
    for (column = 0; column < variant->columns; ++column) {
      unsigned int x;
      unsigned int y;
      if (spec.cells[row][column] == 0)
        continue;
      x = 1u + 3u * column;
      y = 1u + 3u * row;
      output->pixels[y * variant->pixel_width + x] = 1;
      output->pixels[y * variant->pixel_width + x + 1u] = 1;
      output->pixels[(y + 1u) * variant->pixel_width + x] = 1;
      output->pixels[(y + 1u) * variant->pixel_width + x + 1u] = 1;
    }
  }
  for (index = 0; index < variant->edge_count; ++index) {
    BitsquigglesEdge edge;
    unsigned int x;
    unsigned int y;
    if (spec.connections[index] == 0)
      continue;
    edge = edge_at(variant, index);
    x = 1u + 3u * edge.start_column;
    y = 1u + 3u * edge.start_row;
    if (edge.start_row == edge.end_row) {
      output->pixels[y * variant->pixel_width + x + 2u] = 1;
      output->pixels[(y + 1u) * variant->pixel_width + x + 2u] = 1;
    } else {
      output->pixels[(y + 2u) * variant->pixel_width + x] = 1;
      output->pixels[(y + 2u) * variant->pixel_width + x + 1u] = 1;
    }
  }
  for (row = 0; row + 1u < variant->rows; ++row) {
    for (column = 0; column + 1u < variant->columns; ++column) {
      if (spec.connections[edge_index(variant, row, column, row)] &&
          spec.connections[edge_index(variant, row + 1u, column, row + 1u)] &&
          spec.connections[edge_index(variant, row, column, row + 1u)] &&
          spec.connections[edge_index(variant, row, column + 1u,
                                      row + 1u)]) {
        output->pixels[(3u + 3u * row) * variant->pixel_width + 3u +
                       3u * column] = 1;
      }
    }
  }
  output->width = (uint8_t)variant->pixel_width;
  output->height = (uint8_t)variant->pixel_height;
  output->background = spec.background;
  output->foreground = spec.foreground;
  output->style = spec.style;
  return 0;
}

typedef struct {
  uint64_t low;
  uint64_t high;
} EdgeMask;

static EdgeMask edge_mask_bit(unsigned int index) {
  EdgeMask value = {0, 0};
  if (index < 64u)
    value.low = UINT64_C(1) << index;
  else
    value.high = UINT64_C(1) << (index - 64u);
  return value;
}

static EdgeMask edge_mask_or(EdgeMask first, EdgeMask second) {
  EdgeMask value = {first.low | second.low, first.high | second.high};
  return value;
}

static EdgeMask edge_mask_new(EdgeMask required, EdgeMask covered) {
  EdgeMask value = {required.low & ~covered.low,
                    required.high & ~covered.high};
  return value;
}

static bool edge_mask_empty(EdgeMask value) {
  return value.low == 0 && value.high == 0;
}

static bool edge_mask_contains(EdgeMask mask, EdgeMask bit) {
  return (mask.low & bit.low) != 0 || (mask.high & bit.high) != 0;
}

static unsigned int edge_mask_count(EdgeMask value) {
  return popcount64(value.low) + popcount64(value.high);
}

static EdgeMask rectangle_edges(const BitsquigglesVariant *variant,
                                unsigned int top, unsigned int left,
                                unsigned int bottom, unsigned int right,
                                EdgeMask required) {
  EdgeMask result = {0, 0};
  unsigned int row;
  unsigned int column;

  for (row = top; row <= bottom; ++row) {
    for (column = left; column <= right; ++column) {
      if (column < right) {
        EdgeMask bit = edge_mask_bit(
          edge_index(variant, row, column, row));
        if (!edge_mask_contains(required, bit))
          return (EdgeMask){0, 0};
        result = edge_mask_or(result, bit);
      }
      if (row < bottom) {
        EdgeMask bit = edge_mask_bit(
          edge_index(variant, row, column, row + 1u));
        if (!edge_mask_contains(required, bit))
          return (EdgeMask){0, 0};
        result = edge_mask_or(result, bit);
      }
    }
  }
  return result;
}

static uint64_t required_junctions(const BitsquigglesVariant *variant,
                                   EdgeMask required) {
  uint64_t result = 0;
  unsigned int row;
  unsigned int column;
  for (row = 0; row + 1u < variant->rows; ++row) {
    for (column = 0; column + 1u < variant->columns; ++column) {
      if (!edge_mask_empty(rectangle_edges(
              variant, row, column, row + 1u, column + 1u, required))) {
        result |= UINT64_C(1) <<
                  (row * (variant->columns - 1u) + column);
      }
    }
  }
  return result;
}

static uint64_t rectangle_junctions(const BitsquigglesVariant *variant,
                                    unsigned int top, unsigned int left,
                                    unsigned int bottom, unsigned int right,
                                    uint64_t required) {
  uint64_t result = 0;
  unsigned int row;
  unsigned int column;
  for (row = top; row < bottom; ++row) {
    for (column = left; column < right; ++column) {
      uint64_t bit = UINT64_C(1) <<
                     (row * (variant->columns - 1u) + column);
      if ((required & bit) != 0)
        result |= bit;
    }
  }
  return result;
}

static bool better_blob(BitsquigglesSmoothBlob candidate,
                        EdgeMask candidate_edges,
                        uint64_t candidate_junctions,
                        BitsquigglesSmoothBlob best, EdgeMask best_edges,
                        uint64_t best_junctions) {
  unsigned int candidate_count = popcount64(candidate_junctions);
  unsigned int best_count = popcount64(best_junctions);
  unsigned int candidate_area;
  unsigned int best_area;

  if (candidate_count != best_count)
    return candidate_count > best_count;
  candidate_count = edge_mask_count(candidate_edges);
  best_count = edge_mask_count(best_edges);
  if (candidate_count != best_count)
    return candidate_count > best_count;
  candidate_area = (candidate.bottom_row - candidate.top_row + 1u) *
                   (candidate.right_column - candidate.left_column + 1u);
  best_area = (best.bottom_row - best.top_row + 1u) *
              (best.right_column - best.left_column + 1u);
  if (candidate_area != best_area)
    return candidate_area < best_area;
  if (candidate.top_row != best.top_row)
    return candidate.top_row < best.top_row;
  if (candidate.left_column != best.left_column)
    return candidate.left_column < best.left_column;
  if (candidate.bottom_row != best.bottom_row)
    return candidate.bottom_row < best.bottom_row;
  return candidate.right_column < best.right_column;
}

static int generate_smooth_blobs(const BitsquigglesVariant *variant,
                                 const uint8_t *connections,
                                 BitsquigglesSmoothBlob *output) {
  EdgeMask required = {0, 0};
  EdgeMask covered = {0, 0};
  uint64_t required_junction_mask;
  uint64_t covered_junctions = 0;
  unsigned int index;
  unsigned int count = 0;

  if (connections == NULL || output == NULL)
    return -1;
  for (index = 0; index < variant->edge_count; ++index) {
    if (connections[index] > 1u)
      return -1;
    if (connections[index] != 0)
      required = edge_mask_or(required, edge_mask_bit(index));
  }
  required_junction_mask = required_junctions(variant, required);

  while (!edge_mask_empty(edge_mask_new(required, covered)) ||
         (required_junction_mask & ~covered_junctions) != 0) {
    EdgeMask remaining = edge_mask_new(required, covered);
    EdgeMask best_edges = {0, 0};
    uint64_t best_junctions = 0;
    BitsquigglesSmoothBlob best = {0, 0, 0, 0};
    unsigned int anchor_top;
    unsigned int anchor_left;
    unsigned int anchor_bottom;
    unsigned int anchor_right;
    unsigned int top;
    unsigned int left;
    unsigned int bottom;
    unsigned int right;
    bool found = false;

    if (!edge_mask_empty(remaining)) {
      BitsquigglesEdge edge;
      for (index = 0; index < variant->edge_count; ++index) {
        if (edge_mask_contains(remaining, edge_mask_bit(index)))
          break;
      }
      if (index == variant->edge_count)
        return -1;
      edge = edge_at(variant, index);
      anchor_top = edge.start_row;
      anchor_left = edge.start_column;
      anchor_bottom = edge.end_row;
      anchor_right = edge.end_column;
    } else {
      uint64_t remaining_junctions =
          required_junction_mask & ~covered_junctions;
      unsigned int junction_count =
          (variant->rows - 1u) * (variant->columns - 1u);
      for (index = 0; index < junction_count; ++index) {
        if ((remaining_junctions & (UINT64_C(1) << index)) != 0)
          break;
      }
      anchor_top = index / (variant->columns - 1u);
      anchor_left = index % (variant->columns - 1u);
      anchor_bottom = anchor_top + 1u;
      anchor_right = anchor_left + 1u;
    }

    for (top = anchor_top + 1u; top-- > 0;) {
      for (left = anchor_left + 1u; left-- > 0;) {
        for (bottom = anchor_bottom; bottom < variant->rows; ++bottom) {
          for (right = anchor_right; right < variant->columns; ++right) {
            EdgeMask candidate_edges = rectangle_edges(
                variant, top, left, bottom, right, required);
            EdgeMask new_edges;
            uint64_t candidate_junctions;
            uint64_t new_junctions;
            BitsquigglesSmoothBlob candidate;
            if (edge_mask_empty(candidate_edges))
              continue;
            candidate_junctions = rectangle_junctions(
                variant, top, left, bottom, right, required_junction_mask);
            new_edges = edge_mask_new(candidate_edges, covered);
            new_junctions = candidate_junctions & ~covered_junctions;
            candidate.top_row = (uint8_t)top;
            candidate.left_column = (uint8_t)left;
            candidate.bottom_row = (uint8_t)bottom;
            candidate.right_column = (uint8_t)right;
            if ((!edge_mask_empty(new_edges) || new_junctions != 0) &&
                (!found || better_blob(
                               candidate, new_edges, new_junctions, best,
                               edge_mask_new(best_edges, covered),
                               best_junctions & ~covered_junctions))) {
              found = true;
              best = candidate;
              best_edges = candidate_edges;
              best_junctions = candidate_junctions;
            }
          }
        }
      }
    }
    if (!found || count >= variant->max_smooth_blobs)
      return -1;
    output[count++] = best;
    covered = edge_mask_or(covered, best_edges);
    covered_junctions |= best_junctions;
  }
  return (int)count;
}

int bitsquiggles_mix(BitsquigglesWidth width, uint64_t input,
                     uint64_t *output) {
  const BitsquigglesVariant *variant = variant_for_width(width);
  if (variant == NULL || output == NULL || input > variant->input_mask)
    return -1;
  *output = mix_value(variant, input);
  return 0;
}

int bitsquiggles_bip380_checksum_input(const char *checksum,
                                       uint64_t *output) {
  static const char charset[] = "qpzry9x8gf2tvdw0s3jn54khce6mua7l";
  uint64_t value = 0;
  unsigned int index;

  if (checksum == NULL || output == NULL || strlen(checksum) != 8u)
    return -1;
  for (index = 0; index < 8u; ++index) {
    const char *character = strchr(charset, checksum[index]);
    if (character == NULL)
      return -1;
    value = (value << 5) | (uint64_t)(character - charset);
  }
  *output = value;
  return 0;
}

unsigned int
bitsquiggles_free_connection_count(BitsquigglesWidth width,
                                   BitsquigglesMode mode) {
  return free_connection_count(variant_for_width(width), (unsigned int)mode);
}

unsigned int
bitsquiggles_usable_connection_count(BitsquigglesWidth width,
                                     BitsquigglesMode mode) {
  return usable_connection_count(variant_for_width(width), (unsigned int)mode);
}

bool bitsquiggles_matches_mode(BitsquigglesWidth width,
                              const uint8_t *connections,
                              BitsquigglesMode mode) {
  return matches_mode(variant_for_width(width), connections,
                      (unsigned int)mode);
}

int bitsquiggles_edges(BitsquigglesWidth width, BitsquigglesEdge *output) {
  const BitsquigglesVariant *variant = variant_for_width(width);
  if (variant == NULL || output == NULL)
    return -1;
  generate_edges(variant, output);
  return (int)variant->edge_count;
}

const char *bitsquiggles_mode_label(BitsquigglesMode mode) {
  static const char *const labels[] = {"A|", "A-", "A+", "A/"};
  unsigned int index = (unsigned int)mode;
  return valid_mode(index) ? labels[index] : NULL;
}

int bitsquiggles_spec(BitsquigglesWidth width, uint64_t input,
                      BitsquigglesStyle style, BitsquigglesSpec *output) {
  return generate_spec(variant_for_width(width), input, (unsigned int)style,
                       output);
}

int bitsquiggles_pixels(BitsquigglesWidth width, uint64_t input,
                        BitsquigglesStyle style,
                        BitsquigglesPixelGrid *output) {
  return generate_pixels(variant_for_width(width), input, (unsigned int)style,
                         output);
}

int bitsquiggles_smooth_blobs(BitsquigglesWidth width,
                              const uint8_t *connections,
                              BitsquigglesSmoothBlob *output) {
  const BitsquigglesVariant *variant = variant_for_width(width);
  if (variant == NULL)
    return -1;
  return generate_smooth_blobs(variant, connections, output);
}
